<a href="https://colab.research.google.com/github/shaleenjain28/DS/blob/main/Fods2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import linalg

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Show original matrices
print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Addition
add = A + B
print("\nAddition (A + B):\n", add)

# Subtraction
sub = A - B
print("\nSubtraction (A - B):\n", sub)

# Matrix multiplication
matmul = A @ B  # or np.dot(A, B)
print("\nMatrix Multiplication (A @ B):\n", matmul)

# Element-wise multiplication
elem_mul = A * B
print("\nElement-wise Multiplication (A * B):\n", elem_mul)

# Determinant
det_A = linalg.det(A)
print("\nDeterminant of A:", det_A)

# Inverse
inv_A = linalg.inv(A)
print("\nInverse of A:\n", inv_A)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Addition (A + B):
 [[ 6  8]
 [10 12]]

Subtraction (A - B):
 [[-4 -4]
 [-4 -4]]

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]

Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]

Determinant of A: -2.0

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
import numpy as np
from scipy import linalg

# Define matrix
A = np.array([[1, 2], [3, 4]])

# Show original matrix
print("Original Matrix A:\n", A)

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = linalg.eig(A)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors (each column is an eigenvector corresponding to the eigenvalue):\n", eigenvectors)

# Check orthogonality of eigenvectors
v1 = eigenvectors[:, 0]
v2 = eigenvectors[:, 1]

# Dot product should be zero for orthogonal vectors
dot_product = np.dot(np.conj(v1), v2)
print("\nDot Product of eigenvectors v1 and v2:", dot_product)

if np.isclose(dot_product, 0):
    print("→ Eigenvectors are orthogonal")
else:
    print("→ Eigenvectors are not orthogonal")

Original Matrix A:
 [[1 2]
 [3 4]]

Eigenvalues:
 [-0.37228132+0.j  5.37228132+0.j]

Eigenvectors (each column is an eigenvector corresponding to the eigenvalue):
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Dot Product of eigenvectors v1 and v2: -0.17149858514250893
→ Eigenvectors are not orthogonal


In [ ]:
from sympy import Matrix

# Define vectors
v1 = [1, 2, 3]
v2 = [2, 4, 6]
v3 = [1, 0, 1]

# Create a matrix with vectors as rows
M = Matrix([v1, v2, v3])

# Show original matrix
print("Original Matrix (each row is a vector):\n", M)

# Use row-reduced echelon form (RREF) to find the basis
rref_matrix, pivot_columns = M.rref()

print("\nRow Reduced Echelon Form (RREF):\n", rref_matrix)
print("Pivot Columns (indexes of linearly independent vectors):", pivot_columns)

# Basis of the vector space (take original vectors corresponding to pivot rows)
basis_vectors = [M.row(i) for i in pivot_columns]

print("\nBasis Vectors of the Vector Space:")
for vec in basis_vectors:
    print(vec)

print(f"\n→ The span is the space formed by all linear combinations of these {len(basis_vectors)} basis vector(s).")

Original Matrix (each row is a vector):
 Matrix([[1, 2, 3], [2, 4, 6], [1, 0, 1]])

Row Reduced Echelon Form (RREF):
 Matrix([[1, 0, 1], [0, 1, 1], [0, 0, 0]])
Pivot Columns (indexes of linearly independent vectors): (0, 1)

Basis Vectors of the Vector Space:
Matrix([[1, 2, 3]])
Matrix([[2, 4, 6]])

→ The span is the space formed by all linear combinations of these 2 basis vector(s).
